spring:
  application:
    name: hr-api-gateway

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8765
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 20000

zuul:
  routes:
    worker:
      service-id: hr-worker
      path: /hr-worker/**
    
    payroll:
      service-id: hr-payroll
      path: /hr-payroll/**

    user:
      service-id: hr-user
      path: /hr-user/**

    oauth:
      service-id: hr-oauth
      path: /hr-oauth/**
      
