spring:
  application:
    name: hr-config-server

  zipkin:
    base-url: http://localhost:9411

  sleuth:
    sampler:
      probability: 1.0
    
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/marcosvrc/ms_spring_boot_cloud_config
          
          username: marcosvrc
          password: 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
    
server:
  port: 8888
  
  
