spring:
  application:
    name: hr-config-server

  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/marcosvrc/ms_spring_boot_cloud_config
          
          username:
          password:
    
server:
  port: 8888
  
  
