spring:
  application:
    name: hr-eureka-server

  zipkin:
    base-url: http://localhost:9411

  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8761


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
